export const ActionTypes = {
    GET_CART_ITEMS_NUMBERS: "GET_CART_ITEMS_NUMBERS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    EMPTY_CART: "EMPTY_CART"
}